### ISSUE TITLE
Seeking Solution for Restoring Original IMEI on GL-iNet Modem

### ISSUE THREAD

**Issue by behzads2** [srlabs/blue-merle#24]
is there solution to restore a modem to its original IMEI?
 I have already physically reset the router and reinstalled the latest firmware version from GL-iNet, but the IMEI has not reverted to the original.

**Comment by easthvan** [comment]
Hello @behzads2 Yes but not with blue Merle but with standard AT command for this Quectel modem which you can find here in the forum or by Google in an AT commands pdf

**Comment by behzads2** [comment]
Thank you , it's working 
@easthvan manual input IMEI it's great idea !

**Comment by muelli** [comment]
Unfortunately, I'm not aware of getting hold of the original IMEI.
You can try `AT+QPRTPARA=3` to reset the modem to factory defaults.
We could probably offer a button in the Web UI.

**Comment by easthvan** [comment]
> Unfortunately, I'm not aware of getting hold of the original IMEI.
> You can try `AT+QPRTPARA=3` to reset the modem to factory defaults.
> We could probably offer a button in the Web UI.

Regarding the above AT command for modem reset, there is a quite interesting writing here: [link](https://wirelessjoint.com/viewtopic.php?p=16090#p16090) where they mention a secret EGMR code as well...!

"Quectel likes for us to play puzzle games and doesnt include commands in all manuals. The QMBNCFG commands are in the BG96 MBN Application note manual:
Quectel_BG96_MBN_Application_Note_V1.0.pdfThe EGMR command is a protected command that is a not allowed to be supported here on this forum. It is not in any manuals.

The AT+QPRTPARA command I still haven't found in an official manual and was told by Quectel it was a command that was for internal Quectel use only, which is baloney but....

**I do know AT+QPRTPARA=3 will factory wipe your modem, including rewriting the original IMEI. I also believe they say that using it is very hard on the NVRAM and can damage it if used too much,** though I have not seen it. My belief is that its usually not needed.
If you do use it, then the command AT+QPRTPARA=1 is absolutely necessary. This command forces the modem to start saving all parameters to NVRAM properly. Otherwise your modem will lose all settings changes after a hard reset or power cycle. I had to learn this one the hard way."

**Comment by Linuzifer** [comment]
Wiping the original IMEI is the essential core idea of blue merle. You may find it printed on a sticker on your device.
